services:
  mongodb:
    image: mongo:8.0.29-noble
    container_name: nest-o3-mongodb
    restart: unless-stopped
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=1
      MONGO_INITDB_ROOT_USERNAME: pokedex
      MONGO_INITDB_ROOT_PASSWORD: pokedex
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--quiet',
          '--username',
          'pokedex',
          '--password',
          'pokedex',
          '--authenticationDatabase',
          'admin',
          '--eval',
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
