@host = localhost
@port = 3000
@baseUrl = http://{{host}}:{{port}}
@carId = replace-with-an-existing-uuid
@brandId = ba6ce8d2-d7b3-45c5-ac17-c6e255155ee7

## Seed
### Execute seed
GET {{baseUrl}}/seed
Accept: application/json

## Cars
### Get all cars
GET {{baseUrl}}/cars
Accept: application/json

### Get a car by ID
GET {{baseUrl}}/cars/{{carId}}
Accept: application/json

### Create a car
POST {{baseUrl}}/cars
Content-Type: application/json

{
  "brand": "Nissan",
  "model": "Versa"
}

### Partially update a car
PATCH {{baseUrl}}/cars/{{carId}}
Content-Type: application/json

{
  "brand": "Audi"
}

### Delete a car
DELETE {{baseUrl}}/cars/{{carId}}
Accept: application/json

## Brands

### Get all brands
GET {{baseUrl}}/brands
Accept: application/json

### Get a brand by ID
GET {{baseUrl}}/brands/{{brandId}}
Accept: application/json

### Create a brand
POST {{baseUrl}}/brands
Content-Type: application/json

{
  "name": "Nissan"
}

### Partially update a brand
PATCH {{baseUrl}}/brands/{{brandId}}
Content-Type: application/json

{
  "name": "Honda"
}

### Delete a brand
DELETE {{baseUrl}}/brands/{{brandId}}
Accept: application/json
